Make it possible to configure if icons are shown.
aaronshaf/react-toggle pull request #34
Opened 2015-11-18 16:08 UTC by tow8ie

This change allows to disable the display of the “X” and the “checkmark” icon with a new `showIcons` property which is set to `true` by default so that it mimics react-toggle’s old behavior in the standard case.

2016-10-03 22:09 UTC, ahstro requested changes
I like this feature; if you resolve the merge conflicts, I'll test it out and see if it works as intended :)

Thank you!

2016-10-05 16:35 UTC, ahstro commented on index.es6.js
> +            {this.props.showIcons ? <X /> : ''}
Could you use `null` intead of empty string literals for these? IMO, it makes it clearer what we're trying to do. :)

2016-10-05 19:11 UTC, tow8ie commented on index.es6.js
> +            {this.props.showIcons ? <X /> : ''}
No problem.

2016-10-05 19:13 UTC, tow8ie commented
I’m not able to work on this PR before Tuesday. But I’ll prepare it for a merge as soon as I have time to do so.

2016-10-05 19:14 UTC, ahstro commented
No problem, no rush :)

2016-10-10 19:28 UTC, ahstro commented
Moving milestone from this PR to the issue where it is being discussed (#56) :)

2016-11-16 18:02 UTC, ahstro commented
Implemented by #70. Sorry I took a PR that was opened after this, but you didn't respond :/

2016-11-16 18:02 UTC, closed without merging